host: golang-vercel.vercel.app
info:
  contact: {}
  description: API Documentation for Golang deployment in vercel serverless environment
  title: Golang Vercel Deployment
  version: "1.0"
paths:
  /hello/:name:
    get:
      consumes:
      - application/json
      description: Endpoint to Welcome user and say Hello "Name"
      parameters:
      - description: Name in the URL param
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: object
        "400":
          description: Request Error or parameter missing
          schema:
            type: object
        "404":
          description: When user not found
          schema:
            type: object
        "500":
          description: Server Error
          schema:
            type: object
      summary: Hello User
      tags:
      - Welcome
schemes:
- https
- http
swagger: "2.0"
